name: unscramble_qrcode_reader

description: multi qrcode reader
author: borislav nikolov <borislav.nikolov@booking.com>
homepage: https://github.com/jackdoe/scrambled-eggs
version: 0.1.0

flutter:
  plugin:
    androidPackage: com.scrambledeggs.flutter.unscramble.qrcodereader
    pluginClass: QRCodeReaderPlugin

dependencies:
  flutter:
    sdk: flutter

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"
